<?php
$title = 'Add new movie';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('movie', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('director'));
echo $this->formRow($form->get('year'));
echo $this->formRow($form->get('genre'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
