<?php
 // module/Book/view/book/book/edit.phtml:

 $title = 'Edit book';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'book',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('title'));
 echo $this->formRow($form->get('author'));
 echo $this->formRow($form->get('year'));
 echo $this->formRow($form->get('type'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();